In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
data = np.array([[ 3, -1.5,  2, -5.4],
                 [ 0,  4,  -0.3, 2.1],
                 [ 1,  3.3, -1.9, -4.3]])

In [4]:
data_standardized = preprocessing.scale(data)
print data_standardized

print 'Mean =',data_standardized.mean(axis=0)
print 'Std deviation =', data_standardized.std(axis=0)


[[ 1.33630621 -1.40451644  1.29110641 -0.86687558]
 [-1.06904497  0.84543708 -0.14577008  1.40111286]
 [-0.26726124  0.55907936 -1.14533633 -0.53423728]]
Mean = [  5.55111512e-17  -1.11022302e-16  -7.40148683e-17  -7.40148683e-17]
Std deviation = [ 1.  1.  1.  1.]


In [7]:
# min max scaling
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled = data_scaler.fit_transform(data)
print data
print data_scaled


[[ 3.  -1.5  2.  -5.4]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]
[[ 1.          0.          1.          0.        ]
 [ 0.          1.          0.41025641  1.        ]
 [ 0.33333333  0.87272727  0.          0.14666667]]


In [10]:
# normalization
data_normalized = preprocessing.normalize(data, norm='l1')
print data_normalized

[[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [18]:
# binarization
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print data>1.4
print data_binarized

[[ True False  True False]
 [False  True False  True]
 [False  True False False]]
[[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  1.  0.  0.]]


In [24]:
# one hot encoding
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0, 2, 1, 12], [1, 3, 5, 3], [2, 3, 2, 12], [1, 2, 4, 3]])
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print encoded_vector

[[ 0.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]
